<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>HTF2025_Client</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />
      <PackageReference Include="System.Net.Http.Json" Version="9.0.9" />
    </ItemGroup>

</Project>
